# https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html#creating-the-second-package-in-the-workspace
[workspace]
members = [
    "simple_logger",
    "redux",
    "macro",
    "ansi_color",
    "test_fixtures",
    "log",
    "script",
    "tuify",
    "core",
    "md_parser_ng",
]
resolver = "2"
